[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
solc_version = "0.8.19"
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/"
]

[rpc_endpoints]
hyper_mainnet = "${HYPER_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
